// frontend/src/components/ThemeToggle.vue
<script setup lang="ts">
import { Moon, Sun } from 'lucide-vue-next'
import { useTheme } from '@/composables/useTheme'

const { isDark, toggle } = useTheme()
</script>

<template>
  <button
    class="glass-control theme-toggle"
    :title="isDark ? '切换到浅色' : '切换到深色'"
    @click="toggle"
  >
    <component :is="isDark ? Sun : Moon" :size="18" />
  </button>
</template>

<style scoped>
.theme-toggle {
  position: fixed;
  top: 1rem;
  right: 1rem;
  z-index: 50;
  justify-content: center;
  width: 2.5rem;
  height: 2.5rem;
  padding: 0;
}
</style>

// src/Frontend/Heartbeat.Web/src/components/layout/ThemeToggle.tsx
"use client";

import { Icon } from "@/components/ui/Icon";
import { useTheme } from "@/lib/theme";

export function ThemeToggle() {
  const { isDark, toggle } = useTheme();
  return (
    <button
      type="button"
      className="theme-toggle"
      title={isDark ? "切换到浅色" : "切换到深色"}
      aria-label={isDark ? "切换到浅色" : "切换到深色"}
      onClick={toggle}
    >
      <Icon name={isDark ? "sun" : "moon"} size={18} />
    </button>
  );
}
